server:
  port: 8814

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cardmng
    username: seungpro
    password: seungpro
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          description:
#            sql: trace