name: Development CI

on:
  push:
    branch: [development]

jobs:
  build:
    name: start_CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/development' }}

      - name : Execute Gradle build
        run : ./gredlew build

